typography_spectrum: 0.4527825
color:
  saturation: 0.851468
  lightness: 0.9394829
  brandStrength: 0.3777403
  brandColors:
    - '#FCFCFC'
    - '#D5C4B3'
    - '#A87E3F'
    - '#0F0E0D'
    - '#663F1A'
  rhythmicContrast: 0.2194484
layout_spectrum: 1
author:
  name: Rafael Sampaio Nunes Marques
  email: r.global@icloud.com
  url: rdesignglobal.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ffc8936f-4400-4d0f-b626-bf6f41bc58ed.png
name: 'OEX - OFICINA EXPERIMENTAL '
navigation:
  - name: 'OEX na Reserva '
    url: 'http://www.a-reserva.org/oficina-experimental/'
    type: external
title: 'OFICINA, EXPERIMENTAL'
description: 'MADEIRA, METAL, VIDRO, CERÃ‚MICA, BICICLETAS, . . . '
